$ErrorActionPreference = 'Stop'
$taskHandSvg = Join-Path $PSScriptRoot 'assets\tutorial-hand.svg'
$taskHandHeader = Join-Path $PSScriptRoot 'tutorial_hand.h'
[xml]$taskHandDocument = Get-Content -LiteralPath $taskHandSvg -Raw -ErrorAction Stop
$taskHandContour = $taskHandDocument.SelectSingleNode("//*[local-name()='path' and @id='hand-contour']")
if (-not $taskHandContour) { throw 'The shared hand contour is missing.' }
$taskHandData = $taskHandContour.GetAttribute('d')
$taskHandTokenPattern = '[MLC]|-?(?:\d+(?:\.\d*)?|\.\d+)'
if ([regex]::Replace($taskHandData, $taskHandTokenPattern, '').Trim(" `t`r`n,").Length) {
    throw 'The hand contour must use absolute M, L and C commands only.'
}
$taskHandTokens = @([regex]::Matches($taskHandData, $taskHandTokenPattern) | ForEach-Object { $_.Value })
$taskHandHash = (Get-FileHash -LiteralPath $taskHandSvg -Algorithm SHA256 -ErrorAction Stop).Hash.ToLowerInvariant()
$taskHandLines = [Collections.Generic.List[string]]::new()
$taskHandLines.Add('#ifndef THREE_FINGER_TUTORIAL_HAND_H')
$taskHandLines.Add('#define THREE_FINGER_TUTORIAL_HAND_H')
$taskHandLines.Add('/* Generated by generate-hand.ps1 from assets/tutorial-hand.svg. */')
$taskHandLines.Add('/* SVG SHA256: ' + $taskHandHash + ' */')
$taskHandLines.Add('static void main_hand_art_path(void *path){')
$taskHandIndex = 0
$taskHandX = 0.0
$taskHandY = 0.0
$taskHandSegments = 0
function Format-HandFloat([double]$Value) {
    return $Value.ToString('0.0###', [Globalization.CultureInfo]::InvariantCulture) + 'f'
}
while ($taskHandIndex -lt $taskHandTokens.Count) {
    $taskHandCommand = $taskHandTokens[$taskHandIndex++]
    $taskHandCount = switch ($taskHandCommand) { 'M' { 2 }; 'L' { 2 }; 'C' { 6 }; default { throw 'An explicit hand path command is required.' } }
    if ($taskHandIndex + $taskHandCount -gt $taskHandTokens.Count) { throw 'Incomplete hand contour.' }
    $taskHandValues = for ($taskHandNumber = 0; $taskHandNumber -lt $taskHandCount; $taskHandNumber++) {
        $taskHandValue = [double]::Parse($taskHandTokens[$taskHandIndex++], [Globalization.CultureInfo]::InvariantCulture)
        if ([double]::IsNaN($taskHandValue) -or [double]::IsInfinity($taskHandValue) -or $taskHandValue -lt 0 -or $taskHandValue -gt 128) { throw 'Invalid hand coordinate.' }
        $taskHandValue
    }
    if ($taskHandCommand -eq 'M') {
        if ($taskHandIndex -ne 3 -or $taskHandValues[0] -ne 32 -or $taskHandValues[1] -ne 107) { throw 'The contour must start at the original wrist.' }
    } else {
        if ($taskHandSegments -eq 0 -and $taskHandIndex -eq $taskHandCount + 1) { throw 'The contour must start with M.' }
        $taskHandArguments = @($taskHandX, $taskHandY) + $taskHandValues
        $taskHandArgumentsText = ($taskHandArguments | ForEach-Object { Format-HandFloat $_ }) -join ','
        $taskHandHelper = if ($taskHandCommand -eq 'C') { 'main_curve' } else { 'main_segment' }
        $taskHandLines.Add('    ' + $taskHandHelper + '(path,' + $taskHandArgumentsText + ');')
        $taskHandSegments++
    }
    $taskHandX = $taskHandValues[-2]
    $taskHandY = $taskHandValues[-1]
}
if ($taskHandSegments -lt 3 -or $taskHandX -ne 73 -or $taskHandY -ne 107) { throw 'The hand contour must retain the original open wrist.' }
$taskHandLines.Add('}')
$taskHandLines.Add('#endif')
[IO.File]::WriteAllText($taskHandHeader, ($taskHandLines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
