#ifndef THREE_FINGER_TUTORIAL_HAND_H
#define THREE_FINGER_TUTORIAL_HAND_H
/* Generated by generate-hand.ps1 from assets/tutorial-hand.svg. */
/* SVG SHA256: 4d255bc285def942bfb5c8a0ae22b13af366fdb2833c9a9aff1609493b43f8cb */
static void main_hand_art_path(void *path){
    main_curve(path,32.0f,107.0f,28.0f,100.0f,18.0f,84.0f,14.0f,74.0f);
    main_curve(path,14.0f,74.0f,7.0f,60.0f,16.0f,56.0f,23.0f,62.0f);
    main_segment(path,23.0f,62.0f,29.0f,72.0f);
    main_segment(path,29.0f,72.0f,29.0f,33.0f);
    main_curve(path,29.0f,33.0f,29.0f,23.0f,42.0f,23.0f,42.0f,33.0f);
    main_segment(path,42.0f,33.0f,42.0f,62.0f);
    main_segment(path,42.0f,62.0f,43.0f,21.0f);
    main_curve(path,43.0f,21.0f,43.0f,10.0f,56.0f,10.0f,56.0f,21.0f);
    main_segment(path,56.0f,21.0f,56.0f,62.0f);
    main_segment(path,56.0f,62.0f,57.0f,31.0f);
    main_curve(path,57.0f,31.0f,57.0f,21.0f,70.0f,21.0f,70.0f,31.0f);
    main_segment(path,70.0f,31.0f,70.0f,64.0f);
    main_curve(path,70.0f,64.0f,70.55f,58.0f,70.9f,54.0f,71.4f,50.0f);
    main_curve(path,71.4f,50.0f,72.05f,45.6f,74.8f,42.2f,77.7f,42.2f);
    main_curve(path,77.7f,42.2f,80.5f,42.2f,82.85f,44.8f,82.8f,48.2f);
    main_curve(path,82.8f,48.2f,82.55f,57.8f,82.2f,67.0f,82.05f,76.0f);
    main_curve(path,82.05f,76.0f,82.0f,80.0f,80.0f,83.7f,80.0f,87.0f);
    main_curve(path,80.0f,87.0f,79.0f,97.0f,75.0f,101.0f,73.0f,107.0f);
}
#endif
